apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster2
spec:
  selector:
    matchLabels:
      app: hamster2
  replicas: 2
  template:
    metadata:
      labels:
        app: hamster2
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: hamster2
          image: registry.k8s.io/ubuntu-slim:0.1
          resources:
            requests:
              cpu: 1
              memory: "500Mi"
            limits:
              memory: "900Mi"
              cpu: 1.5
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"
